title: "Building a JupyterHub Server"
description: "Building a JupyterLab on JupyterHub 0.9.4 Server for Anaconda3, PyTorch 1.0 on NVIDIA cuDNN 7.4."
repository: "tikoehle/pytorch_conda_jupyterhub"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

 defaults:
   # _posts
   - scope:
       path: ""
       type: posts
     values:
       read_time: true

google_site_verification: "e-T36HnFFsA-MDujmdqlGFbiGqnZovigWbubctBfoTE"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-132315884-1"
    
remote_theme: mmistakes/minimal-mistakes
